# Generated by Django 4.0.5 on 2022-06-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entrees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='sorties',
            field=models.IntegerField(default=0),
        ),
    ]
